server:
  port: 8088
dubbo:
  registry:
    protocol: zookeeper
    address: zookeeper://127.0.0.1:2181
    port: 2181
  protocol:
    name: dubbo
    port: 20890
  application:
    name: ${spring.application.name}
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      max-wait: 30000
      query-timeout: 10
      validation-query: SELECT 1
      use-global-data-source-stat: true
      # 默认开启，当前已开启
      stat:
        log-slow-sql: true
        slow-sql-millis: 1000
      # 默认关闭，需手动开启，当前已开启
      slf4j:
        enabled: true
        data-source-log-enabled: false
        connection-log-enabled: false
        statement-log-enabled: false
        result-set-log-enabled: false
      # 默认关闭，需手动开启，当前已开启
      wall:
        enabled: true
        log-violation: true
        throw-exception: false
        config:
          delete-where-none-check: true
      # 默认关闭，需手动开启，当前已关闭
      config:
        enabled: false
      # 默认关闭，需手动开启，当前已关闭
      web-stat:
        enabled: false
      # 默认关闭，需手动开启，当前已关闭
      aop-stat:
        enabled: false
      # 默认关闭，需手动开启，当前已关闭
      stat-view-servlet:
        enabled: false
      transaction:
        rollback-on-commit-failure: true
      mvc:
        servlet:
          load-on-startup: 1
      aop:
        auto: true
        proxy-target-class: true
      http:
        encoding:
          enabled: true
          force: true
          charset: utf-8
        converters:
          preferred-json-mapper: jackson
      jackson:
        default-property-inclusion: non_null
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
        serialization:
          indent_output: true
          write_null_map_values: true
          write_dates_as_timestamps: false
        deserialization:
          fail_on_unknown_properties: false
        parser:
          allow_unquoted_control_chars: true
          allow_single_quotes: true
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #设置严格模式,默认false不启动. 启动后在未匹配到指定数据源时候会抛出异常,不启动则使用默认数据源.
      datasource:
        master:
          url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&allowMultiQueries=true
          username: root
          password: 123456
          driver-class-name: com.mysql.cj.jdbc.Driver